# Generated by Django 3.0.8 on 2020-10-11 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import info_flow.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20)),
                ('cat_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_process_name', models.CharField(max_length=150)),
                ('proc_description', models.TextField(null=True)),
                ('proc_created', models.DateTimeField(auto_now_add=True)),
                ('proc_modified', models.DateTimeField(auto_now=True)),
                ('proc_start_date', models.DateTimeField(blank=True, null=True)),
                ('proc_end_date', models.DateTimeField(blank=True, null=True)),
                ('proc_is_active', models.BooleanField(default=True)),
                ('proc_is_private', models.BooleanField(default=False)),
                ('proc_is_deleted', models.BooleanField(default=False)),
                ('proc_assigned', models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted'), related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
                ('proc_author', models.ForeignKey(on_delete=models.SET('deleted'), related_name='proc_user', to=settings.AUTH_USER_MODEL)),
                ('proc_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_flow.category')),
            ],
            options={
                'ordering': ['-proc_modified', '-proc_created', '-proc_is_active'],
                'permissions': (('check_proc', 'Check proc'),),
            },
        ),
        migrations.CreateModel(
            name='user_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_department', models.CharField(max_length=100)),
                ('user_profile_info', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_status', models.ForeignKey(on_delete=models.SET('deleted'), to='info_flow.user_status')),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_name', models.CharField(max_length=150)),
                ('tasks_description', models.TextField(null=True)),
                ('tasks_created', models.DateTimeField(auto_now_add=True)),
                ('tasks_modified', models.DateTimeField(auto_now=True)),
                ('tasks_start_date', models.DateTimeField(blank=True, null=True)),
                ('tasks_end_date', models.DateTimeField(blank=True, null=True)),
                ('tasks_is_active', models.BooleanField(default=True)),
                ('tasks_is_deleted', models.BooleanField(default=False)),
                ('tasks_assigned', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('tasks_proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_flow.process')),
                ('tasks_tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_title', models.CharField(max_length=150)),
                ('posts_created', models.DateTimeField(auto_now_add=True)),
                ('posts_modified', models.DateTimeField(auto_now=True)),
                ('posts_text', models.TextField()),
                ('posts_is_deleted', models.BooleanField(default=False)),
                ('post_level', models.IntegerField(default=0)),
                ('posts_author', models.ForeignKey(on_delete=models.SET('deleted'), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-post_level', '-posts_created'],
            },
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_created', models.DateTimeField(auto_now_add=True)),
                ('mess_modified', models.DateTimeField(auto_now=True)),
                ('mess_text', models.TextField()),
                ('mess_is_deleted', models.BooleanField(default=False)),
                ('mess_author', models.ForeignKey(on_delete=models.SET('deleted'), to=settings.AUTH_USER_MODEL)),
                ('mess_posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_flow.posts')),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_name', models.CharField(max_length=300)),
                ('files_added', models.DateTimeField(auto_now_add=True)),
                ('files_is_deleted', models.BooleanField(default=False)),
                ('files_document', models.FileField(blank=True, null=True, upload_to=info_flow.models.user_directory_path)),
                ('files_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('files_posts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.posts')),
                ('files_proc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.process')),
                ('files_tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_body', models.TextField(null=True)),
                ('com_created', models.DateTimeField(auto_now_add=True)),
                ('com_modified', models.DateTimeField(auto_now=True)),
                ('com_is_deleted', models.BooleanField(default=False)),
                ('com_author', models.ForeignKey(on_delete=models.SET('deleted'), to=settings.AUTH_USER_MODEL)),
                ('com_proc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.process')),
                ('com_tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.tasks')),
            ],
            options={
                'ordering': ['-com_created'],
            },
        ),
        migrations.CreateModel(
            name='archive_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arch_posts_title', models.CharField(max_length=150)),
                ('arch_posts_created', models.DateTimeField(auto_now_add=True)),
                ('arch_posts_modified', models.DateTimeField(auto_now=True)),
                ('arch_posts_text', models.TextField()),
                ('arch_posts_is_deleted', models.BooleanField(default=False)),
                ('arch_posts_author', models.ForeignKey(on_delete=models.SET('deleted'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
