# Generated by Django 3.0.8 on 2020-08-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='com_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.files'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.files'),
        ),
        migrations.AlterField(
            model_name='process',
            name='proc_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.files'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tasks_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.files'),
        ),
    ]
