# Generated by Django 3.0.8 on 2020-10-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['-proc_modified', '-proc_created', '-proc_is_active'], 'permissions': (('connect_proc', 'Connect process'),)},
        ),
    ]
