# Generated by Django 3.0.8 on 2021-04-11 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patterns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_name', models.CharField(max_length=150)),
                ('pat_is_private', models.BooleanField(default=False)),
                ('pat_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_flow.category')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='tasks_author',
            field=models.ForeignKey(default=1, on_delete=models.SET('2'), related_name='tasks_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archive_posts',
            name='arch_posts_author',
            field=models.ForeignKey(on_delete=models.SET('2'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='com_author',
            field=models.ForeignKey(on_delete=models.SET('2'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='mess_author',
            field=models.ForeignKey(on_delete=models.SET('2'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='posts_author',
            field=models.ForeignKey(on_delete=models.SET('2'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='proc_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('2'), related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='proc_author',
            field=models.ForeignKey(on_delete=models.SET('2'), related_name='proc_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='patterns_elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pele_order', models.IntegerField()),
                ('pele_type', models.IntegerField()),
                ('pele_name', models.CharField(max_length=150)),
                ('pele_desc', models.TextField(null=True)),
                ('pele_proc', models.IntegerField(blank=True, null=True)),
                ('pele_task', models.IntegerField(blank=True, null=True)),
                ('pele_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_flow.patterns')),
            ],
            options={
                'ordering': ['pele_order'],
            },
        ),
    ]
