# Generated by Django 3.0.8 on 2020-08-09 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0002_auto_20200807_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='com_proc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info_flow.process'),
            preserve_default=False,
        ),
    ]
