# Generated by Django 3.0.8 on 2020-10-22 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0002_tasks_tasks_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive_posts',
            name='arch_posts_author',
            field=models.ForeignKey(on_delete=models.SET('2'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='com_author',
            field=models.ForeignKey(on_delete=models.SET('2'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='mess_author',
            field=models.ForeignKey(on_delete=models.SET('2'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='posts_author',
            field=models.ForeignKey(on_delete=models.SET('2'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='proc_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('2'), related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='proc_author',
            field=models.ForeignKey(on_delete=models.SET('2'), related_name='proc_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tasks_author',
            field=models.ForeignKey(on_delete=models.SET('2'), related_name='tasks_user', to=settings.AUTH_USER_MODEL),
        ),
    ]