# Generated by Django 3.0.8 on 2020-10-16 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0002_auto_20201015_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'permissions': (('connect_task', 'Connect task'), ('connect_point', 'Connect point'))},
        ),
        migrations.AlterField(
            model_name='process',
            name='proc_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('1'), related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='proc_author',
            field=models.ForeignKey(on_delete=models.SET('1'), related_name='proc_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
