# Generated by Django 3.0.8 on 2020-08-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0003_comments_com_proc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['proc_created']},
        ),
    ]
