# Generated by Django 3.1 on 2020-10-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0003_auto_20201022_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
