# Generated by Django 3.0.8 on 2020-10-29 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0003_auto_20201022_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='patterns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_name', models.CharField(max_length=150)),
                ('pat_is_private', models.BooleanField(default=False)),
                ('pat_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_flow.category')),
            ],
        ),
        migrations.CreateModel(
            name='patterns_elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pele_type', models.IntegerField()),
                ('pele_name', models.CharField(max_length=150)),
                ('pele_desc', models.TextField(null=True)),
                ('pele_proc', models.IntegerField()),
                ('pele_task', models.IntegerField(blank=True, null=True)),
                ('pele_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_flow.patterns')),
            ],
        ),
    ]