# Generated by Django 3.0.8 on 2020-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0004_auto_20200811_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tasks_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
