# Generated by Django 3.0.8 on 2020-11-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0005_auto_20201030_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterns_elements',
            name='pele_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]