# Generated by Django 3.0.8 on 2020-08-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0005_auto_20200811_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tasks_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
