# Generated by Django 3.1 on 2020-11-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0004_auto_20201022_2017'),
        ('info_flow', '0006_patterns_elements_pele_order'),
    ]

    operations = [
    ]
