# Generated by Django 3.0.8 on 2020-08-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0006_auto_20200811_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['proc_created'], 'permissions': (('can_view', 'Can see processes'),)},
        ),
    ]
