# Generated by Django 3.0.8 on 2022-02-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0007_merge_20201101_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patterns_elements',
            options={'ordering': ['pele_order']},
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
