# Generated by Django 3.0.8 on 2022-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0009_user_wire_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wul',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wup',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
