# Generated by Django 3.0.8 on 2020-08-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0009_auto_20200818_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='mess_is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
