# Generated by Django 3.0.8 on 2020-08-29 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info_flow', '0012_auto_20200829_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='files_user',
            field=models.ForeignKey(default=1, on_delete=models.SET('deleted'), related_name='documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='files_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
