# Generated by Django 3.0.8 on 2020-08-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0013_auto_20200829_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='files_user',
        ),
    ]
