# Generated by Django 3.0.8 on 2020-08-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0019_auto_20200829_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='files_proc',
        ),
    ]
