# Generated by Django 3.0.8 on 2020-08-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0020_remove_files_files_proc'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='files_proc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.process'),
        ),
    ]
