# Generated by Django 3.0.8 on 2020-08-29 10:53

from django.db import migrations, models
import info_flow.models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0021_files_files_proc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='files_document',
            field=models.FileField(blank=True, null=True, upload_to=info_flow.models.user_directory_path),
        ),
    ]
