# Generated by Django 3.0.8 on 2020-08-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0022_auto_20200829_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='files_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.posts'),
        ),
    ]
