# Generated by Django 3.0.8 on 2020-08-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0023_files_files_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='tasks_is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
