# Generated by Django 3.0.8 on 2020-08-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0024_tasks_tasks_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='com_is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
