# Generated by Django 3.0.8 on 2020-08-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0025_comments_com_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='files_is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
