# Generated by Django 3.0.8 on 2020-08-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0026_files_files_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['post_level']},
        ),
        migrations.AddField(
            model_name='posts',
            name='post_level',
            field=models.IntegerField(default=0),
        ),
    ]
