# Generated by Django 3.0.8 on 2020-08-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0027_auto_20200829_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-post_level']},
        ),
    ]
