# Generated by Django 3.0.8 on 2020-09-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0029_auto_20200829_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-post_level', 'posts_modified']},
        ),
        migrations.AddField(
            model_name='tasks',
            name='tasks_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.tasks'),
        ),
    ]
