# Generated by Django 3.0.8 on 2020-09-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0030_auto_20200903_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='files_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.tasks'),
        ),
    ]
