# Generated by Django 3.0.8 on 2020-09-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0031_files_files_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['-proc_modified', '-proc_created', '-proc_is_active'], 'permissions': (('check_proc', 'Check proc'),)},
        ),
    ]
