# Generated by Django 3.0.8 on 2020-09-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0032_auto_20200924_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-post_level', '-posts_created']},
        ),
    ]
