# Generated by Django 3.0.8 on 2020-10-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_flow', '0035_comments_com_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='com_proc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.process'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='com_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_flow.tasks'),
        ),
    ]
