# Generated by Django 3.0.8 on 2022-04-20 16:15

import DBscripts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
                ('report_type', models.CharField(max_length=30)),
                ('base_number', models.IntegerField()),
                ('report_author', models.ForeignKey(on_delete=models.SET('2'), related_name='report_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=300)),
                ('report_path', models.FileField(blank=True, null=True, upload_to=DBscripts.models.report_path)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBscripts.Report')),
            ],
        ),
    ]
