# Generated by Django 3.0.8 on 2022-05-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBscripts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_item',
            old_name='report_path',
            new_name='report_file',
        ),
    ]
