# Generated by Django 3.0.8 on 2022-05-16 15:01

import DBscripts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBscripts', '0002_auto_20220506_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=300)),
                ('report_file', models.FileField(blank=True, null=True, upload_to=DBscripts.models.report_path)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='end',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Report_item',
        ),
        migrations.AddField(
            model_name='reportitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBscripts.Report'),
        ),
    ]
