# Generated by Django 3.0.8 on 2022-06-18 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBscripts', '0003_auto_20220516_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportItemElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=30)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(null=True)),
                ('report_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBscripts.ReportItem')),
            ],
        ),
    ]
