# Generated by Django 3.0.8 on 2021-04-11 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RB_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPlantConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_from', models.DateTimeField(blank=True, null=True)),
                ('dt_to', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('element_type', models.IntegerField()),
                ('POB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PowerplantElement', to='RB_mgmt.Element')),
                ('PowerPlant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PowerPlantItem', to='RB_mgmt.Powerplant')),
                ('author', models.ForeignKey(on_delete=models.SET('1'), related_name='PowerplantConnecionAuthor', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=models.SET('1'), related_name='PowerplantConnecionModifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
