# Generated by Django 3.0.8 on 2021-04-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RB_mgmt', '0002_powerplantconnection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='powerplantconnection',
            old_name='PowerPlant',
            new_name='PowerPlantItem',
        ),
    ]
