# Generated by Django 3.0.8 on 2022-05-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BalancingMarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csprpowerplant',
            name='POB',
        ),
        migrations.AddField(
            model_name='element',
            name='cspr_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='old_skome_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='wire_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerplant',
            name='cspr_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CsprElement',
        ),
        migrations.DeleteModel(
            name='CsprPowerplant',
        ),
    ]
