# Generated by Django 3.0.8 on 2022-05-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BalancingMarket', '0002_auto_20220506_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.IntegerField(choices=[(0, 'Podmiot odpowiedzialny za bilansowanie'), (1, 'Sprzedawca energii')]),
        ),
    ]
