# Generated by Django 3.0.8 on 2022-05-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BalancingMarket', '0003_auto_20220507_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='files_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BalancingMarket.Connection'),
        ),
        migrations.AddField(
            model_name='file',
            name='files_powerplant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BalancingMarket.Powerplant'),
        ),
        migrations.AlterField(
            model_name='file',
            name='files_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BalancingMarket.Element'),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='element_type',
            field=models.IntegerField(choices=[(0, 'Elektrociepłownia'), (1, 'Farma Wiatrowa'), (1, 'Elektrownia Wodna'), (1, 'Fotowoltaika'), (1, 'Biogazownia')]),
        ),
        migrations.DeleteModel(
            name='PowerPlantConnection',
        ),
    ]
