# Generated by Django 3.0.8 on 2022-05-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BalancingMarket', '0004_auto_20220507_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='POB',
            field=models.ForeignKey(limit_choices_to={'element_type': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='POB', to='BalancingMarket.Element'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='SE',
            field=models.ForeignKey(limit_choices_to={'element_type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='SE', to='BalancingMarket.Element'),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='element_type',
            field=models.IntegerField(choices=[(0, 'Elektrociepłownia'), (1, 'Farma Wiatrowa'), (2, 'Elektrownia Wodna'), (3, 'Fotowoltaika'), (4, 'Biogazownia')]),
        ),
    ]
