# Generated by Django 3.0.8 on 2022-05-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BalancingMarket', '0005_auto_20220507_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerplant',
            name='POB',
        ),
        migrations.RemoveField(
            model_name='powerplant',
            name='dt_from',
        ),
        migrations.RemoveField(
            model_name='powerplant',
            name='dt_to',
        ),
        migrations.AddField(
            model_name='element',
            name='rher_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PowerPlantConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_from', models.DateTimeField(blank=True, null=True)),
                ('dt_to', models.DateTimeField(blank=True, null=True)),
                ('POB', models.ForeignKey(limit_choices_to={'element_type': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='PowerplantConnection', to='BalancingMarket.Element')),
            ],
        ),
        migrations.AddField(
            model_name='powerplant',
            name='config',
            field=models.ForeignKey(default=1, limit_choices_to={'element_type': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='PowerplantConnection', to='BalancingMarket.PowerPlantConnection'),
            preserve_default=False,
        ),
    ]
