# Generated by Django 3.0.8 on 2022-05-08 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BalancingMarket', '0006_auto_20220508_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerplant',
            name='config',
        ),
        migrations.AddField(
            model_name='powerplantconnection',
            name='powerplant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Powerplant', to='BalancingMarket.Powerplant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='powerplantconnection',
            name='dt_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='powerplantconnection',
            name='dt_to',
            field=models.DateTimeField(),
        ),
    ]
